import { DashboardPayload, MatchAnalysis } from './types'

export const demoMatches: MatchAnalysis[] = [
  {
    id: '1',
    league: 'Premier League',
    kickoff: '2026-04-17T19:30:00Z',
    status: 'NS',
    home: 'Arsenal',
    away: 'Chelsea',
    homeWin: 54,
    draw: 25,
    awayWin: 21,
    btts: 58,
    over25: 61,
    bestBet: 'Arsenal empate anula',
    market: 'Draw No Bet',
    confidence: 'Alta',
    confidenceScore: 84,
    reasoning: 'Melhor forma recente, mando de campo e defesa mais consistente.',
    odds: 1.62,
  },
  {
    id: '2',
    league: 'Serie A',
    kickoff: '2026-04-17T18:45:00Z',
    status: 'LIVE',
    minute: 54,
    home: 'Inter',
    away: 'Lazio',
    score: '1-0',
    homeWin: 63,
    draw: 22,
    awayWin: 15,
    btts: 45,
    over25: 52,
    bestBet: 'Inter vence',
    market: '1X2',
    confidence: 'Alta',
    confidenceScore: 87,
    reasoning: 'Inter pressiona mais, cria chances claras e controla posse.',
    odds: 1.68,
  },
  {
    id: '3',
    league: 'La Liga',
    kickoff: '2026-04-17T20:00:00Z',
    status: 'NS',
    home: 'Real Madrid',
    away: 'Valencia',
    homeWin: 66,
    draw: 20,
    awayWin: 14,
    btts: 49,
    over25: 57,
    bestBet: 'Real Madrid over 1.5 gols',
    market: 'Team Goals',
    confidence: 'Alta',
    confidenceScore: 89,
    reasoning: 'Ataque forte em casa e visitante cede volume alto de finalizações.',
    odds: 1.55,
  },
  {
    id: '4',
    league: 'Bundesliga',
    kickoff: '2026-04-17T18:30:00Z',
    status: 'NS',
    home: 'Bayern',
    away: 'Mainz',
    homeWin: 72,
    draw: 17,
    awayWin: 11,
    btts: 46,
    over25: 65,
    bestBet: 'Bayern vence e over 1.5',
    market: 'Bet Builder',
    confidence: 'Alta',
    confidenceScore: 91,
    reasoning: 'Superioridade ofensiva e grande volume criado contra defesas frágeis.',
    odds: 1.74,
  },
]

export const demoDashboard: DashboardPayload = {
  summary: {
    initialBankroll: 1000,
    currentBankroll: 1128,
    totalStaked: 420,
    totalProfit: 128,
    roi: 30.48,
    wins: 7,
    losses: 3,
    voids: 1,
  },
  topSuggestion: demoMatches[3],
  todayMatches: demoMatches,
  singles: [demoMatches[3], demoMatches[2], demoMatches[1]],
  multiples: [
    {
      id: 'm1',
      label: 'Múltipla Conservadora',
      selections: [
        { match: 'Bayern x Mainz', selection: 'Bayern vence', odds: 1.35 },
        { match: 'Inter x Lazio', selection: 'Inter empate anula', odds: 1.28 },
        { match: 'Real Madrid x Valencia', selection: 'Real Madrid over 1.5 gols', odds: 1.55 },
      ],
      combinedOdds: 2.68,
      risk: 'Baixo',
    },
    {
      id: 'm2',
      label: 'Múltipla de Valor',
      selections: [
        { match: 'Arsenal x Chelsea', selection: 'Arsenal empate anula', odds: 1.62 },
        { match: 'Bayern x Mainz', selection: 'Over 2.5 gols', odds: 1.44 },
        { match: 'Real Madrid x Valencia', selection: 'Casa vence', odds: 1.38 },
      ],
      combinedOdds: 3.22,
      risk: 'Médio',
    },
  ],
  recentBets: [
    {
      id: 'b1',
      match: 'Liverpool x Brighton',
      market: '1X2',
      selection: 'Liverpool vence',
      odds: 1.67,
      stake: 40,
      result: 'win',
      profit: 26.8,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'b2',
      match: 'Milan x Torino',
      market: 'Over/Under',
      selection: 'Over 2.5',
      odds: 1.88,
      stake: 30,
      result: 'loss',
      profit: -30,
      createdAt: new Date().toISOString(),
    },
  ],
}
